owner: algebratech # Your GitHub organization or username, where this repository lives
repo: coffeeon-status-page # The name of this repository

sites:
  - name: Mobile Staging API
    url: https://api-test.coffeeon.global
  - name: M2M API
    url: https://mqtt-service.coffeeon.global/staging/api/alive/

status-website:
  cname: status.coffeeon.global
  # baseUrl: /your-repo-name
  logoUrl: https://s3.eu-central-1.amazonaws.com/algebra.assets/algebra_logo_a_small.png
  name: Coffeeon
  introTitle: "**Coffeeon** status page shows the operational availability of services"
  introMessage: This is a detailed page which shows you a great overview of current health of running services.
  navbar:
    - title: Status
      href: /
